version: '3.9'
services:
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: emqu_backend
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        networks:
            - emqu
        ports:
            - 8000:80

    database:
        image: mariadb:latest
        container_name: emqu_db
        restart: unless-stopped
        networks:
            - emqu
        environment:
            - MYSQL_DATABASE=emqu_db
            - MYSQL_USER=emqu_user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306

networks:
    emqu:
        driver: bridge

volumes:
    db_data:
        driver: local
